"""add discord identity fields to loan assignments

Revision ID: 55b916b59dde
Revises: 48d97f3eb650
Create Date: 2026-07-24 01:27:05.740727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b916b59dde'
down_revision: Union[str, Sequence[str], None] = '48d97f3eb650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_user_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('mtgo_username', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_assignments', schema=None) as batch_op:
        batch_op.drop_column('mtgo_username')
        batch_op.drop_column('discord_user_id')

    # ### end Alembic commands ###
