"""Create cube card relation

Revision ID: 5a569fe4f8fa
Revises: 6e08821a95a3
Create Date: 2026-07-17 11:40:19.374441

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a569fe4f8fa'
down_revision: Union[str, Sequence[str], None] = '6e08821a95a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cube_cards',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('cube_id', sa.Integer(), nullable=False),
                    sa.Column('card_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
                    sa.ForeignKeyConstraint(['cube_id'], ['cubes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cube_cards')
    # ### end Alembic commands ###
