"""Add card metadata

Revision ID: 5ede70dfaa6f
Revises: 616d81239dd1
Create Date: 2026-07-17 11:30:50.405754

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ede70dfaa6f'
down_revision: Union[str, Sequence[str], None] = '616d81239dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('mtgo_name', sa.String(length=255), nullable=True))
    op.add_column('cards', sa.Column('set_code', sa.String(length=10), nullable=True))
    op.add_column('cards', sa.Column('collector_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'collector_number')
    op.drop_column('cards', 'set_code')
    op.drop_column('cards', 'mtgo_name')
    # ### end Alembic commands ###
