"""Create cards table

Revision ID: 616d81239dd1
Revises: 
Create Date: 2026-07-17 11:27:02.224840

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '616d81239dd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('scryfall_id', sa.String(length=36), nullable=True),
                    sa.Column('oracle_id', sa.String(length=36), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
