"""Add CubeCobra id

Revision ID: eee767a17a1e
Revises: a306c8c4f11c
Create Date: 2026-07-17 12:38:08.889490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee767a17a1e'
down_revision: Union[str, Sequence[str], None] = 'a306c8c4f11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cubes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cubecobra_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cubes', schema=None) as batch_op:
        batch_op.drop_column('cubecobra_id')

    # ### end Alembic commands ###
